export type Metric = {
  label: string;
  value: string;
  delta: string;
  tone: string;
  detail?: string;
};

export type Customer = {
  id: string;
  name: string;
  contact_person?: string;
  phone?: string;
  email?: string;
  address?: string;
  segment?: string;
  status?: string;
  pipeline_stage?: string;
  lead_source?: string;
  account_owner?: string;
  next_follow_up?: string;
  preferred_channel?: string;
  date_of_birth?: string;
  anniversary_date?: string;
  gstin?: string;
  pan?: string;
  state?: string;
  place_of_supply?: string;
  dpdp_consent?: string;
  dpdp_consent_at?: string;
  marketing_consent?: string;
  dlt_reference?: string;
  consent_notes?: string;
  notes?: string;
  assigned_staff_ids?: string[];
  assigned_team_summary?: string;
  primary_account_owner?: string;
};

export type SiteVisit = {
  id: string;
  customer_id: string;
  visit_number?: number;
  customer_name?: string;
  address?: string;
  site_person_name?: string;
  site_person_mobile?: string;
  reference_given_by?: string;
  reference_mobile?: string;
  pit_size_mm?: string;
  machine_room_available?: string;
  site_visit_date?: string;
  site_offer_no?: string;
  site_enquiry_no?: string;
  floor_height_profile?: string;
  opening_schedule?: Array<{
    floor: string;
    ff_height_mm: string;
    lintel_height_mm: string;
  }>;
  site_offer_type?: string;
  site_motor_required?: string;
  site_finish_required?: string;
  site_door_required?: string;
  site_number_of_openings?: string;
  site_stops?: string;
  site_opening_type?: string;
  door_size_width_mm?: string;
  door_size_height_mm?: string;
  car_size_width_mm?: string;
  car_size_depth_mm?: string;
  site_capacity_persons?: string;
  site_capacity_kg?: string;
  shaft_width_mm?: string;
  shaft_depth_mm?: string;
  brick_wall_available?: string;
  civil_door_height_mm?: string;
  visited_by?: string;
  submitted_by?: string;
  submitted_by_username?: string;
  submitted_by_department?: string;
  submitted_by_staff_id?: string;
  updated_by?: string;
  updated_by_username?: string;
  created_at?: string;
  updated_at?: string;
  notes?: string;
};

export type Estimate = {
  id: string;
  customer_id?: string;
  customer_name: string;
  site?: string;
  elevator_type?: string;
  offer_type?: string;
  job_no?: string;
  offer_date?: string;
  stops?: string;
  capacity?: string;
  speed?: string;
  drive_type?: string;
  door_type?: string;
  finish?: string;
  material_cost?: number;
  install_cost?: number;
  overhead_cost?: number;
  margin_percent?: number;
  margin_amount?: number;
  discount?: number;
  gst_percent?: number;
  gst_amount?: number;
  calculated_total_cost?: number;
  offer_valid_until?: string;
  payment_terms?: string;
  delivery_timeline?: string;
  warranty_terms?: string;
  offer_letter_status?: string;
  inventory_material_total?: number;
  inventory_pricing_source?: string;
  inventory_items?: Array<{
    item_id?: string;
    name?: string;
    category?: string;
    unit?: string;
    qty?: string | number;
    current_price?: string | number;
    purchase_price?: string | number;
    price_date?: string;
    vendor?: string;
  }>;
  site_visit_id?: string;
  site_measurements_source?: string;
  site_address?: string;
  pit_size_mm?: string;
  machine_room_available?: string;
  floor_height_profile?: string;
  site_stops?: string;
  site_number_of_openings?: string;
  site_opening_type?: string;
  door_size_width_mm?: string;
  door_size_height_mm?: string;
  car_size_width_mm?: string;
  car_size_depth_mm?: string;
  site_capacity_persons?: string;
  site_capacity_kg?: string;
  shaft_width_mm?: string;
  shaft_depth_mm?: string;
  brick_wall_available?: string;
  civil_door_height_mm?: string;
  opening_schedule_summary?: string;
  opening_schedule?: Array<{
    floor: string;
    ff_height_mm: string;
    lintel_height_mm: string;
  }>;
  status?: string;
  total_cost?: number;
  created_at?: string;
};

export type PortalData = {
  [key: string]: unknown;
  metrics: Metric[];
  customers: Customer[];
  site_visits: SiteVisit[];
  estimates: Estimate[];
  inventory?: Array<Record<string, unknown>>;
  platform_modules?: Array<Record<string, unknown>>;
  project_tickets?: Array<Record<string, unknown>>;
  install_jobs?: Array<Record<string, unknown>>;
  install_team?: Array<Record<string, unknown>>;
  installation_contractors?: Array<Record<string, unknown>>;
  users?: Array<Record<string, unknown>>;
  fleet?: Array<Record<string, unknown>>;
  renewals?: Array<Record<string, unknown>>;
  work_orders?: Array<Record<string, unknown>>;
  international_vendors?: Array<Record<string, unknown>>;
  marketing_assets?: Array<Record<string, unknown>>;
  tenders?: Array<Record<string, unknown>>;
  customer_assignments?: Array<Record<string, unknown>>;
  department_assignments?: Array<Record<string, unknown>>;
  time_tracking?: Array<Record<string, unknown>>;
  department_history?: Array<Record<string, unknown>>;
  attendance_today?: Array<Record<string, unknown>>;
  org_chart?: Array<Record<string, unknown>>;
  leave_requests?: Array<Record<string, unknown>>;
  payments?: Array<Record<string, unknown>>;
  viewer?: { display_name?: string; username?: string; department?: string; role?: string; linked_org_node?: string; linked_team_member?: string };
  access?: { allowed_views?: string[]; selected_view?: string; default_view?: string; is_restricted?: boolean };
  synced_at?: string;
};
